sdk: "/Users/brian/work/rhodes"
sdkversion: 2.0.0
name: bars
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["barcode"]
capabilities:
  - camera
