--- 
extensions: 
- json
- another-extension
name: IssueTracker-rhodes
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.5
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.2.6
iphone: 
  BundleURLScheme: IssueTracker-rhodes
  provisionprofile: 
  BundleIdentifier: com.rhomobile.IssueTracker-rhodes
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
