--- 
extensions: 
- extension-name-here
- second-extension-name
name: pimalerts
capabilities: 
- pim
- vibrate
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.0.0.rc1
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.0.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
android:
  version: 2.1